
version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: Spring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  # 추가
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus


